#pragma once

// TAPPING_TERM
#ifdef TAPPING_TERM
#  undef TAPPING_TERM
#endif

#define TAPPING_TERM 140

#define IGNORE_MOD_TAP_INTERRUPT
#define PREVENT_STUCK_MODIFIERS
#define FORCE_NKRO
#define RGBLIGHT_SLEEP

#define FORCE_NKRO
